#!/bin/sh

# VBoxManage list runningvms
# VBoxManage startvm centos-7 --type headless
# VBoxManage controlvm centos-7 acpipowerbutton

if [ "X$1" == "Xstart" ]
then
    VBoxManage startvm centos-7 --type headless
elif [ "X$1" == "Xlist" ]
then
    VBoxManage list runningvms
elif [ "X$1" == "Xshutdown" ]
then
    VBoxManage controlvm centos-7 acpipowerbutton
elif [ "X$1" == "Xstop" ]
then
    sshpass -pdawter ssh root@cs7 poweroff
else
    sshpass -pdawter ssh root@cs7
fi
