#!/bin/bash

print_usage()
{
    echo "$0:"
    echo " -a       (-d,-v,-i) dump, validate and inject back"
    echo " -s       Dump first sealed chunk data"
    echo " -v       Validate dumped chunk copies"
    echo " -i       Inject back chunk data"
    echo " -h host  Host address"
    echo " -f file  Chunkid file"
    echo " -v       Verbos"
    exit 1
}

if [[ $BASH_VERSINFO < 4 ]]
then
    echo "You bash version: $BASH_VERSION"
    echo "This script need bash 4.0 or later"
    exit 0
fi

ipaddr=$(hostname -i)
chunkidfile='chunkid.list'
search_mode='ACTIVE'

if [ $# -lt 1 ]
then
    print_usage
fi

while getopts ':f:h:savi' opt
do
    case $opt in
    f) chunkidfile=$OPTARG
    ;;
    h) ipaddr=$OPTARG
    ;;
    i) inject_back='TRUE'
    ;;
    s) search_mode='SEALED'
    ;;
    v) validate_data='VALIDATE'
    ;;
    ?) echo 'error'
       print_usage
    ;;
    esac
done

if [ ! -e "$chunkidfile" ]
then
    echo "$chunkidfile not exist"
    print_usage
fi

eval $(curl -s "http://${ipaddr}:9101/stats/ssm/varraycapacity/" | awk -F'[<>]' '/VarrayId/{printf "cos=\047%s\047\n",$3}')
if [ "x${cos}" == "x" ]
then
    echo "can not get cos of ${ipaddr}"
    print_usage
fi

# map public ip to private ip to use viprexec
declare -A ipmap=()
eval $(getrackinfo | awk 'NF==8{printf "ipmap[\"%s\"]=%s\n",$5, $1}')
#echo ${ipmap[$public_ip]}

while read -u 99 chunkid
do
    echo "chunkid   : $chunkid"
    mkdir -p $chunkid
    curl -s "http://${ipaddr}:9101/diagnostic/1/ShowChunkInfo?cos=${cos}&chunkid=${chunkid}" > $chunkid/${chunkid}.info
    # get chunk primary(zone) and sealedTime
    eval $(awk '/primary/{printf "zone=%s\n",$2};/sealedTime:/{printf "sealedTime=\047%s\047\n",$2}' $chunkid/${chunkid}.info)
    echo "zone      : $zone"
    echo "sealedTime: $sealedTime"
    # get chunk dtId
    curl -s "http://${ipaddr}:9101/diagnostic/CT/1/DumpAllKeys/CHUNK?chunkId=${chunkid}&useStyle=raw" | grep -B1 schemaType > $chunkid/${chunkid}.dtId
    eval $(awk -F/ '/http/{printf "dtId=\047%s\047\n",$4}' $chunkid/${chunkid}.dtId)
    echo "dtId      : $dtId"
    # List JR(Journal Region)
    curl -s "http://${ipaddr}:9101/diagnostic/PR/2/DumpAllKeys/DIRECTORYTABLE_RECORD?type=JOURNAL_REGION&dtId=${dtId}&zone=${zone}&useStyle=raw&showvalue=gpb"|grep -B1 schemaType > $chunkid/${chunkid}.JR
    # get JR url
    eval $(awk 'NR==1 && /http/{printf "jr_url=\047%s\047\n",$0}' $chunkid/${chunkid}.JR)
    echo "JR_URL    : $jr_url"
    curl -s "${jr_url%$'\r'}" > $chunkid/${chunkid}.JRDetail
    for ((timestamp=sealedTime-400000000; timestamp<=sealedTime+8000000000; timestamp+=1))
    do
        eval $(awk -v timeval=$timestamp '$1~/schemaType/{major=$10} $1~/timestamp:/{if($2>timeval) {printf "major=%s;timestamp=%s\n",major,$2;exit}}' $chunkid/${chunkid}.JRDetail)
        # Dump JR content
        if [[ "x$major" != "x" ]]
        then
            startline=""
            curl -s "http://${ipaddr}:9101/journalcontent/${dtId}?zone=${zone}&major=$major" > $chunkid/${chunkid}.JRContent.${major}
            eval $(awk -v chunkid="$chunkid" -v cstatus="$search_mode" 'BEGIN{flag=0}/schemaType CHUNK chunkId/,/isEc: false/{if($1=="<schemaKey>schemaType" && $2=="CHUNK" && $4~chunkid){flag=1}else if($1=="<schemaKey>schemaType" && $2=="CHUNK" && $4!~chunkid){flag=0}else if($1=="<value>status:" && $2==cstatus && flag){printf "startline=%d\n",NR;exit}else{next}}' $chunkid/${chunkid}.JRContent.${major})
            if [ "x$startline" != "x" ]
            then
                echo "major     : $major"
                echo "timestamp : $timestamp"
                for ((i=1; i<=2; i++))
                do
                    echo "startline   : $startline"
                    ssId=""
                    partitionId=""
                    filename=""
                    eval $(awk -v startline=$startline 'BEGIN{flag=1}NR>=startline{if($1~"ssId"){printf "ssId=%s;",$2}else if($1~"partitionId"){printf "partitionId=%s;",$2}else if($1~"filename"){printf "filename=%s;",$2}else if($1~"offset"&&flag){flag=0;printf "offset=%d;",$2/100}else if($1~"endOffset"){printf "endOffset=%d;startline=%s\n",$2/100,NR+3; exit}}' $chunkid/${chunkid}.JRContent.${major})

                    echo "ssId        : $ssId"
                    echo "partitionId : $partitionId"
                    echo "filename    : $filename"
                    echo "offset      : $offset"
                    echo "endOffset   : $endOffset"
                    echo viprexec -n ${ipmap[$ssId]} --dock=object-main \'"dd if=/dae/uuid-${partitionId}/${filename} of=/var/log/${chunkid}.copy${i} bs=100 skip=${offset} count=${endOffset}"\'
                    viprexec -n ${ipmap[$ssId]} --dock=object-main \'"dd if=/dae/uuid-${partitionId}/${filename} of=/var/log/${chunkid}.copy${i} bs=100 skip=${offset} count=${endOffset}"\'
                    echo scp ${ipmap[$ssId]}:/opt/emc/caspian/fabric/agent/services/object/main/log/${chunkid}.copy${i} ${chunkid}/${chunkid}.copy${i}
                    scp ${ipmap[$ssId]}:/opt/emc/caspian/fabric/agent/services/object/main/log/${chunkid}.copy${i} ${chunkid}/${chunkid}.copy${i}
                done
                # break for loop
                break
            else
                rm -f $chunkid/${chunkid}.JRContent.${major}
            fi
        else
            echo "major not find"
        fi
    done
    echo '<<  ----------- process finished -----------  >>'
done 99< $chunkidfile

